### ISSUE TITLE
Document Socket methods

### ISSUE THREAD

**Issue by navarr** [navarr/Sockets#2]

**Comment by jsturdevant** [comment]
I'll help out with this. I've already forked and I am documenting now. Do you have any specific formats or tools you use? I've used [phpdoc](https://www.phpdoc.org/) previously to generate HTML docs based on the comments.

**Comment by navarr** [comment]
Phpdoc is what I'd like it to be documented in. Most of it will likely be duplicating it from PHP itself for the object.
